title: Wangjian Wu's Homepage
page-top-title: Wangjian Wu(吴汪箭)
top-section-bg-text: Data Science
home-subtitle: Wangjian Wu&ensp;|&ensp;吴汪箭
copyright-text: '&copy; Wangjian Wu 2022-2026. All Rights Reserved.'
